### PR TITLE
add new nightly chores: cleanup and backup

### PR DESCRIPTION
**Pull request by marykatefain**
Added new nightly chores: cleanup and backup Tried to stick to the same "every other day" offset pattern, with the backup being kinda random in between. Pls review.

### CODE REVIEW

**Comment by alexgleason** [comment]
This isn't going to do anything without URLs

**Comment by marykatefain** [comment]
Good catch! Just updated the PR. TY

**Comment by alexgleason** [comment]
Do you want to continue adding bad code to this or fix it?

**Comment by marykatefain** [comment]
Let's go ahead and deploy this for now because the roommates are down my throat about it - I can work on refactor referenced in #5 tomorrow, maybe!

**Pull request merged**
